/**
 * The build-your-own-avatar vocabulary (SXU brief: "optional profile image
 * or selected illustrated avatar; do not require a photograph"). Instead of
 * picking one of six fixed medallions, a student composes her own portrait
 * from a small set of facets — skin tone, hair style, hair colour, her
 * expression, and a crown. Every facet is illustrated in-app (no photos, no
 * uploads, nothing generated by an external service, nothing to moderate).
 *
 * The composed choice is stored as a small structured object on
 * student_profiles.avatar_config; the art lives in AvatarCoin.tsx. Facet
 * VALUES double as the render keys and as the swatch/label source for the
 * builder UI, so this file is the single source of truth for both. The
 * server mirrors these key sets in student-profile/index.ts (same pattern as
 * the strengths vocabulary) — when a facet gains an option, update both.
 *
 * Skin and hair palettes are their own configured dataset (they can't come
 * from the 12-colour brand palette); the crown and coin backdrop tie back to
 * branding.config so the avatar still reads as part of the brand's world.
 */

export type AvatarFacetId = 'skin' | 'hair' | 'hairColor' | 'expression' | 'crown';

/** The five facets, in the order the builder presents them. */
export type AvatarConfig = Record<AvatarFacetId, string>;

export type AvatarOption = {
  key: string;
  label: string;
  /** The dot shown in the builder's swatch row. */
  swatch: string;
};

export type AvatarFacet = {
  id: AvatarFacetId;
  /** The girl-facing name of the facet. */
  label: string;
  options: readonly AvatarOption[];
};

/** Skin tones — warm and inclusive; the fill also drives the ear shapes. */
const SKIN_TONES: readonly AvatarOption[] = [
  { key: 'porcelain', label: 'Porcelain', swatch: '#F7D9C4' },
  { key: 'honey', label: 'Honey', swatch: '#EFC1A0' },
  { key: 'golden', label: 'Golden', swatch: '#D99C77' },
  { key: 'amber', label: 'Amber', swatch: '#B87A50' },
  { key: 'chestnut', label: 'Chestnut', swatch: '#8D5A38' },
  { key: 'espresso', label: 'Espresso', swatch: '#5C3A26' },
] as const;

const HAIR_STYLES: readonly AvatarOption[] = [
  { key: 'afro', label: 'Afro', swatch: '#2B2320' },
  { key: 'coils', label: 'Coils', swatch: '#2B2320' },
  { key: 'braids', label: 'Braids', swatch: '#2B2320' },
  { key: 'waves', label: 'Waves', swatch: '#2B2320' },
  { key: 'straight', label: 'Straight', swatch: '#2B2320' },
  { key: 'bun', label: 'Bun', swatch: '#2B2320' },
] as const;

const HAIR_COLORS: readonly AvatarOption[] = [
  { key: 'black', label: 'Black', swatch: '#1C1712' },
  { key: 'espresso', label: 'Espresso', swatch: '#3B2A1E' },
  { key: 'chestnut', label: 'Chestnut', swatch: '#6B4429' },
  { key: 'auburn', label: 'Auburn', swatch: '#8C3B22' },
  { key: 'honey', label: 'Honey', swatch: '#B67A3D' },
] as const;

const EXPRESSIONS: readonly AvatarOption[] = [
  { key: 'smile', label: 'Smile', swatch: '#2C2320' },
  { key: 'calm', label: 'Calm', swatch: '#2C2320' },
  { key: 'joyful', label: 'Joyful', swatch: '#2C2320' },
  { key: 'cool', label: 'Cool', swatch: '#2C2320' },
] as const;

const CROWNS: readonly AvatarOption[] = [
  { key: 'classic', label: 'Classic crown', swatch: '#F0B0A0' },
  { key: 'tiara', label: 'Tiara', swatch: '#F0B0A0' },
  { key: 'flowers', label: 'Flower crown', swatch: '#E05070' },
  { key: 'halo', label: 'Halo', swatch: '#F0B0A0' },
  { key: 'none', label: 'No crown', swatch: 'transparent' },
] as const;

export const AVATAR_FACETS: readonly AvatarFacet[] = [
  { id: 'skin', label: 'Skin', options: SKIN_TONES },
  { id: 'hair', label: 'Hair', options: HAIR_STYLES },
  { id: 'hairColor', label: 'Hair colour', options: HAIR_COLORS },
  { id: 'expression', label: 'Expression', options: EXPRESSIONS },
  { id: 'crown', label: 'Crown', options: CROWNS },
] as const;

/** A gentle, representative starting point for a girl who hasn't built one. */
export const DEFAULT_AVATAR_CONFIG: AvatarConfig = {
  skin: 'golden',
  hair: 'coils',
  hairColor: 'black',
  expression: 'smile',
  crown: 'classic',
};

const OPTION_KEYS: Readonly<Record<AvatarFacetId, ReadonlySet<string>>> = {
  skin: new Set(SKIN_TONES.map((o) => o.key)),
  hair: new Set(HAIR_STYLES.map((o) => o.key)),
  hairColor: new Set(HAIR_COLORS.map((o) => o.key)),
  expression: new Set(EXPRESSIONS.map((o) => o.key)),
  crown: new Set(CROWNS.map((o) => o.key)),
};

const SKIN_FILL = new Map(SKIN_TONES.map((o) => [o.key, o.swatch]));
const HAIR_FILL = new Map(HAIR_COLORS.map((o) => [o.key, o.swatch]));

export function skinFill(key: string): string {
  return SKIN_FILL.get(key) ?? '#D99C77';
}

export function hairFill(key: string): string {
  return HAIR_FILL.get(key) ?? '#1C1712';
}

/** True only for an object carrying exactly the five known facets, each a
 * known option — the client-side mirror of the server's validation. */
export function isAvatarConfig(value: unknown): value is AvatarConfig {
  if (typeof value !== 'object' || value === null) {
    return false;
  }
  const record = value as Record<string, unknown>;
  for (const facet of AVATAR_FACETS) {
    const picked = record[facet.id];
    if (typeof picked !== 'string' || !OPTION_KEYS[facet.id].has(picked)) {
      return false;
    }
  }
  return true;
}

export function optionLabel(facetId: AvatarFacetId, key: string): string {
  const facet = AVATAR_FACETS.find((f) => f.id === facetId);
  return facet?.options.find((o) => o.key === key)?.label ?? key;
}

/** A short, screen-reader-friendly description of a composed avatar. */
export function describeAvatar(config: AvatarConfig): string {
  const crown = config.crown === 'none' ? 'no crown' : optionLabel('crown', config.crown);
  return (
    `${optionLabel('skin', config.skin)} skin, ` +
    `${optionLabel('hairColor', config.hairColor)} ${optionLabel('hair', config.hair)} hair, ` +
    `${optionLabel('expression', config.expression)} expression, ${crown}`
  );
}
