/**
 * The build-your-own-avatar vocabulary (SXU brief: "optional profile image
 * or selected illustrated avatar; do not require a photograph"). A student
 * composes her own portrait from facets — skin tone, face shape, eyes, nose,
 * mouth, hair style, hair colour, and a crown. Everything is illustrated
 * in-app (no photos, no uploads, nothing generated by an external service,
 * nothing to moderate).
 *
 * The composed choice is stored as a small structured object on
 * student_profiles.avatar_config; the art lives in AvatarCoin.tsx. Facet
 * VALUES double as the render keys and the swatch/label source for the
 * builder UI, so this file is the single source of truth. The server mirrors
 * these key sets in student-profile/index.ts (same discipline as the
 * strengths vocabulary) — when a facet gains an option, update both.
 *
 * The illustrated SVG here is the interim art; a commissioned layered asset
 * set (docs/AVATAR_ILLUSTRATION_SPEC.md) drops into this same harness with no
 * change to the vocabulary or storage.
 */

export type AvatarFacetId =
  'skin' | 'faceShape' | 'eyes' | 'nose' | 'mouth' | 'hair' | 'hairColor' | 'crown';

export type AvatarConfig = Record<AvatarFacetId, string>;

export type AvatarOption = {
  key: string;
  label: string;
  /** The dot shown in the builder's swatch row. */
  swatch: string;
};

export type AvatarFacet = {
  id: AvatarFacetId;
  label: string;
  options: readonly AvatarOption[];
};

/** Skin tones — warm and inclusive; the fill also drives the ear/nose art. */
const SKIN_TONES: readonly AvatarOption[] = [
  { key: 'porcelain', label: 'Porcelain', swatch: '#F7D9C4' },
  { key: 'honey', label: 'Honey', swatch: '#EFC1A0' },
  { key: 'golden', label: 'Golden', swatch: '#D99C77' },
  { key: 'amber', label: 'Amber', swatch: '#B87A50' },
  { key: 'chestnut', label: 'Chestnut', swatch: '#8D5A38' },
  { key: 'espresso', label: 'Espresso', swatch: '#5C3A26' },
] as const;

// Face outline shapes — the neutral dot is a placeholder; the label carries
// the meaning (a shape isn't a colour).
const FACE_SHAPES: readonly AvatarOption[] = [
  { key: 'round', label: 'Round', swatch: '#E9C9B3' },
  { key: 'oval', label: 'Oval', swatch: '#E9C9B3' },
  { key: 'heart', label: 'Heart', swatch: '#E9C9B3' },
  { key: 'square', label: 'Square', swatch: '#E9C9B3' },
  { key: 'long', label: 'Long', swatch: '#E9C9B3' },
] as const;

const EYES: readonly AvatarOption[] = [
  { key: 'round', label: 'Round', swatch: '#3A2A28' },
  { key: 'almond', label: 'Almond', swatch: '#3A2A28' },
  { key: 'wide', label: 'Wide', swatch: '#3A2A28' },
  { key: 'soft', label: 'Soft', swatch: '#3A2A28' },
] as const;

const NOSES: readonly AvatarOption[] = [
  { key: 'button', label: 'Button', swatch: '#C79A80' },
  { key: 'round', label: 'Rounded', swatch: '#C79A80' },
  { key: 'wide', label: 'Wide', swatch: '#C79A80' },
  { key: 'narrow', label: 'Narrow', swatch: '#C79A80' },
] as const;

const MOUTHS: readonly AvatarOption[] = [
  { key: 'smile', label: 'Smile', swatch: '#B4566A' },
  { key: 'full', label: 'Full lips', swatch: '#B4566A' },
  { key: 'grin', label: 'Grin', swatch: '#B4566A' },
  { key: 'soft', label: 'Soft', swatch: '#B4566A' },
] as const;

// Black-hair-forward styles, each rendered with texture and worn off the face.
const HAIR_STYLES: readonly AvatarOption[] = [
  { key: 'afro', label: 'Afro', swatch: '#2B2320' },
  { key: 'coils', label: 'Coils', swatch: '#2B2320' },
  { key: 'locs', label: 'Locs', swatch: '#2B2320' },
  { key: 'braids', label: 'Box braids', swatch: '#2B2320' },
  { key: 'cornrows', label: 'Cornrows', swatch: '#2B2320' },
  { key: 'ponytail', label: 'Ponytail', swatch: '#2B2320' },
  { key: 'puffs', label: 'Puffs', swatch: '#2B2320' },
] as const;

const HAIR_COLORS: readonly AvatarOption[] = [
  { key: 'black', label: 'Black', swatch: '#1C1712' },
  { key: 'espresso', label: 'Espresso', swatch: '#3B2A1E' },
  { key: 'chestnut', label: 'Chestnut', swatch: '#6B4429' },
  { key: 'auburn', label: 'Auburn', swatch: '#8C3B22' },
  { key: 'honey', label: 'Honey', swatch: '#B67A3D' },
] as const;

const CROWNS: readonly AvatarOption[] = [
  { key: 'classic', label: 'Classic crown', swatch: '#F0B0A0' },
  { key: 'tiara', label: 'Tiara', swatch: '#F0B0A0' },
  { key: 'flowers', label: 'Flower crown', swatch: '#E05070' },
  { key: 'halo', label: 'Halo', swatch: '#F0B0A0' },
  { key: 'none', label: 'No crown', swatch: 'transparent' },
] as const;

export const AVATAR_FACETS: readonly AvatarFacet[] = [
  { id: 'skin', label: 'Skin', options: SKIN_TONES },
  { id: 'faceShape', label: 'Face shape', options: FACE_SHAPES },
  { id: 'eyes', label: 'Eyes', options: EYES },
  { id: 'nose', label: 'Nose', options: NOSES },
  { id: 'mouth', label: 'Mouth', options: MOUTHS },
  { id: 'hair', label: 'Hair', options: HAIR_STYLES },
  { id: 'hairColor', label: 'Hair colour', options: HAIR_COLORS },
  { id: 'crown', label: 'Crown', options: CROWNS },
] as const;

/** A gentle, representative starting point for a girl who hasn't built one. */
export const DEFAULT_AVATAR_CONFIG: AvatarConfig = {
  skin: 'golden',
  faceShape: 'round',
  eyes: 'round',
  nose: 'button',
  mouth: 'smile',
  hair: 'coils',
  hairColor: 'black',
  crown: 'classic',
};

const OPTION_KEYS: Readonly<Record<AvatarFacetId, ReadonlySet<string>>> = {
  skin: new Set(SKIN_TONES.map((o) => o.key)),
  faceShape: new Set(FACE_SHAPES.map((o) => o.key)),
  eyes: new Set(EYES.map((o) => o.key)),
  nose: new Set(NOSES.map((o) => o.key)),
  mouth: new Set(MOUTHS.map((o) => o.key)),
  hair: new Set(HAIR_STYLES.map((o) => o.key)),
  hairColor: new Set(HAIR_COLORS.map((o) => o.key)),
  crown: new Set(CROWNS.map((o) => o.key)),
};

const SKIN_FILL = new Map(SKIN_TONES.map((o) => [o.key, o.swatch]));
const HAIR_FILL = new Map(HAIR_COLORS.map((o) => [o.key, o.swatch]));

export function skinFill(key: string): string {
  return SKIN_FILL.get(key) ?? '#D99C77';
}

export function hairFill(key: string): string {
  return HAIR_FILL.get(key) ?? '#1C1712';
}

/** True only for an object carrying exactly the known facets, each a known
 * option — the client-side mirror of the server's validation. */
export function isAvatarConfig(value: unknown): value is AvatarConfig {
  if (typeof value !== 'object' || value === null) {
    return false;
  }
  const record = value as Record<string, unknown>;
  for (const facet of AVATAR_FACETS) {
    const picked = record[facet.id];
    if (typeof picked !== 'string' || !OPTION_KEYS[facet.id].has(picked)) {
      return false;
    }
  }
  return true;
}

export function optionLabel(facetId: AvatarFacetId, key: string): string {
  const facet = AVATAR_FACETS.find((f) => f.id === facetId);
  return facet?.options.find((o) => o.key === key)?.label ?? key;
}

/** A short, screen-reader-friendly description of a composed avatar. */
export function describeAvatar(config: AvatarConfig): string {
  const crown = config.crown === 'none' ? 'no crown' : optionLabel('crown', config.crown);
  return (
    `${optionLabel('skin', config.skin)} skin, ${optionLabel('faceShape', config.faceShape)} face, ` +
    `${optionLabel('hairColor', config.hairColor)} ${optionLabel('hair', config.hair)} hair, ` +
    `${optionLabel('eyes', config.eyes)} eyes, ${optionLabel('mouth', config.mouth)} mouth, ${crown}`
  );
}
