/**
 * AvatarCoin — renders a student's composed avatar (AvatarConfig) as a warm
 * illustrated portrait inside a circular coin. All art is drawn in-app from
 * her facet choices: no photograph, no upload, nothing generated by an
 * external service. Layer order back→front: backdrop, hair (behind), neck,
 * head, ears, face, hair (framing), crown.
 *
 * Skin/hair colours come from the avatar vocabulary; the crown and backdrop
 * read from branding.config so the coin stays inside the brand's world.
 * Reused wherever a student's mark appears — the builder preview today, the
 * app bar and Share feed once those carry avatars.
 */
import { useId, type ReactNode } from 'react';
import { describeAvatar, hairFill, skinFill, type AvatarConfig } from '@/lib/avatarBuilder';
import { brand } from '@/config/branding.config';

const FEATURE = '#2C2320';
const HEAD = { cx: 50, cy: 50, r: 23 } as const;

const COIL_BUMPS: readonly [number, number][] = [
  [34, 32],
  [44, 26],
  [56, 26],
  [66, 32],
  [27, 44],
  [73, 44],
];
const FLOWER_POS: readonly [number, number][] = [
  [38, 30],
  [50, 27],
  [62, 30],
];

function hairArt(style: string, color: string): { back: ReactNode; front: ReactNode | null } {
  switch (style) {
    case 'afro':
      return { back: <circle cx={50} cy={45} r={30} fill={color} />, front: null };
    case 'coils':
      return {
        back: (
          <g fill={color}>
            <circle cx={50} cy={46} r={27} />
            {COIL_BUMPS.map(([cx, cy]) => (
              <circle key={`${String(cx)}-${String(cy)}`} cx={cx} cy={cy} r={6} />
            ))}
          </g>
        ),
        front: null,
      };
    case 'braids':
      return {
        back: <circle cx={50} cy={44} r={26} fill={color} />,
        front: (
          <g stroke={color} strokeLinecap="round" fill="none">
            <path d="M30,46 V73" strokeWidth={7} />
            <path d="M70,46 V73" strokeWidth={7} />
            <g stroke={FEATURE} strokeOpacity={0.25} strokeWidth={1.4}>
              <path d="M27,54 h6M27,62 h6M27,70 h6" />
              <path d="M67,54 h6M67,62 h6M67,70 h6" />
            </g>
          </g>
        ),
      };
    case 'waves':
      return {
        back: (
          <path
            d="M27,40 Q21,60 30,80 Q40,73 50,80 Q60,73 70,80 Q79,60 73,40 Q50,30 27,40 Z"
            fill={color}
          />
        ),
        front: <path d="M29,38 Q50,27 71,38 Q60,43 50,40 Q40,43 29,38 Z" fill={color} />,
      };
    case 'straight':
      return {
        back: <path d="M28,42 Q50,25 72,42 Q50,35 28,42 Z" fill={color} />,
        front: (
          <g fill={color}>
            <path d="M27,41 L27,72 Q30,75 33,72 L33,47 Q28,44 27,41 Z" />
            <path d="M73,41 L73,72 Q70,75 67,72 L67,47 Q72,44 73,41 Z" />
          </g>
        ),
      };
    case 'bun':
    default:
      return {
        back: (
          <g fill={color}>
            <circle cx={50} cy={46} r={25} />
            <circle cx={50} cy={21} r={8} />
          </g>
        ),
        front: null,
      };
  }
}

function Face({ expression }: { expression: string }) {
  const cheeks = (
    <g fill={brand.colors.primary} opacity={0.28}>
      <circle cx={38} cy={57} r={3.4} />
      <circle cx={62} cy={57} r={3.4} />
    </g>
  );
  if (expression === 'calm') {
    return (
      <g>
        {cheeks}
        <g stroke={FEATURE} strokeWidth={2} strokeLinecap="round">
          <path d="M39,50 h5" />
          <path d="M56,50 h5" />
        </g>
        <path
          d="M44,61 Q50,63 56,61"
          stroke={FEATURE}
          strokeWidth={2}
          fill="none"
          strokeLinecap="round"
        />
      </g>
    );
  }
  if (expression === 'joyful') {
    return (
      <g>
        {cheeks}
        <g stroke={FEATURE} strokeWidth={2.2} strokeLinecap="round" fill="none">
          <path d="M39,51 Q41.5,47 44,51" />
          <path d="M56,51 Q58.5,47 61,51" />
        </g>
        <path
          d="M42,59 Q50,68 58,59"
          stroke={FEATURE}
          strokeWidth={2.4}
          fill="none"
          strokeLinecap="round"
        />
      </g>
    );
  }
  if (expression === 'cool') {
    return (
      <g>
        {cheeks}
        <g stroke={FEATURE} strokeWidth={1.6} strokeLinecap="round">
          <path d="M38,45 h7" />
          <path d="M55,45 h7" />
        </g>
        <ellipse cx={42} cy={50} rx={1.9} ry={2.3} fill={FEATURE} />
        <ellipse cx={58} cy={50} rx={1.9} ry={2.3} fill={FEATURE} />
        <path
          d="M43,61 Q49,63 58,60"
          stroke={FEATURE}
          strokeWidth={2}
          fill="none"
          strokeLinecap="round"
        />
      </g>
    );
  }
  // smile (default)
  return (
    <g>
      {cheeks}
      <ellipse cx={42} cy={50} rx={1.9} ry={2.3} fill={FEATURE} />
      <ellipse cx={58} cy={50} rx={1.9} ry={2.3} fill={FEATURE} />
      <path
        d="M43,60 Q50,66 57,60"
        stroke={FEATURE}
        strokeWidth={2.2}
        fill="none"
        strokeLinecap="round"
      />
    </g>
  );
}

function Crown({ kind }: { kind: string }) {
  const gold = brand.colors.crownGold;
  const edge = brand.colors.secondary;
  if (kind === 'none') {
    return null;
  }
  if (kind === 'tiara') {
    return (
      <g stroke={edge} strokeWidth={1} strokeLinejoin="round">
        <path d="M37,32 Q50,22 63,32 Q50,28 37,32 Z" fill={gold} />
        <circle cx={50} cy={26.5} r={2.4} fill={brand.colors.primary} stroke="none" />
      </g>
    );
  }
  if (kind === 'flowers') {
    return (
      <g stroke="none">
        {FLOWER_POS.map(([cx, cy]) => (
          <g key={`${String(cx)}-${String(cy)}`}>
            <circle cx={cx} cy={cy} r={4} fill={brand.colors.primary} />
            <circle cx={cx} cy={cy} r={1.7} fill={gold} />
          </g>
        ))}
      </g>
    );
  }
  if (kind === 'halo') {
    return <ellipse cx={50} cy={17} rx={15} ry={4} fill="none" stroke={gold} strokeWidth={2.6} />;
  }
  // classic
  return (
    <g stroke={edge} strokeWidth={1} strokeLinejoin="round">
      <path d="M35,33 L38,22 L44,29 L50,18 L56,29 L62,22 L65,33 Z" fill={gold} />
      <g fill={brand.colors.primary} stroke="none">
        <circle cx={38} cy={22} r={1.5} />
        <circle cx={50} cy={18} r={1.7} />
        <circle cx={62} cy={22} r={1.5} />
      </g>
    </g>
  );
}

export function AvatarCoin({
  config,
  size = 96,
  title,
}: {
  config: AvatarConfig;
  size?: number;
  title?: string | undefined;
}) {
  const id = useId();
  const clipId = `${id}-clip`;
  const bgId = `${id}-bg`;
  const skin = skinFill(config.skin);
  const hair = hairArt(config.hair, hairFill(config.hairColor));

  return (
    <svg
      className="avatar-coin-svg"
      width={size}
      height={size}
      viewBox="0 0 100 100"
      role="img"
      aria-label={title ?? describeAvatar(config)}
    >
      <defs>
        <clipPath id={clipId}>
          <circle cx={50} cy={50} r={50} />
        </clipPath>
        <radialGradient id={bgId} cx="50%" cy="38%" r="75%">
          <stop offset="0%" stopColor={brand.colors.surfaceLight} />
          <stop offset="100%" stopColor={brand.colors.accent} />
        </radialGradient>
      </defs>
      <g clipPath={`url(#${clipId})`}>
        <circle cx={50} cy={50} r={50} fill={`url(#${bgId})`} />
        {hair.back}
        {/* Neck first, then shoulders over its base, then the head over the
            neck top — so there's no gap between chin and shoulders. */}
        <rect x={44} y={62} width={12} height={18} rx={5} fill={skin} />
        <path d="M18,100 Q18,80 50,80 Q82,80 82,100 Z" fill={brand.colors.secondary} />
        <circle cx={HEAD.cx} cy={HEAD.cy} r={HEAD.r} fill={skin} />
        <circle cx={28} cy={53} r={3.2} fill={skin} />
        <circle cx={72} cy={53} r={3.2} fill={skin} />
        <Face expression={config.expression} />
        {hair.front}
        <Crown kind={config.crown} />
      </g>
    </svg>
  );
}
